name: CMake

on: [push, pull_request]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
      fail-fast: false
    steps:
    - uses: actions/checkout@v2
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
    - name: windeployqt
      if: startsWith(matrix.os, 'windows')
      run: |
        windeployqt ${{github.workspace}}/build/src/gui/${{env.BUILD_TYPE}} --release --no-compiler-runtime --no-translations --no-opengl-sw
        windeployqt ${{github.workspace}}/build/src/${{env.BUILD_TYPE}} --release --no-compiler-runtime --no-translations --no-opengl-sw
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: piet-${{ matrix.os }}
        path: ${{github.workspace}}/build
