name: CMake

on: [push, pull_request]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
      fail-fast: false
    steps:
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
    # <Doxygen>
    - name: Install Doxygen (windows)
      if: startsWith(matrix.os, 'windows')
      run: choco install doxygen.install texlive
    - name: Install Doxygen (ubuntu)
      if: startsWith(matrix.os, 'ubuntu')
      run: sudo apt install -y doxygen texlive-full
    - name: Install Doxygen (macos)
      if: startsWith(matrix.os, 'macos')
      run: brew install doxygen texlive
    # </Doxygen>
    - uses: actions/checkout@v2
    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
    - name: Build docs
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
    - name: Create export dir
      run: |
        mkdir ${{github.workspace}}/export
        mkdir ${{github.workspace}}/export/bin
        mkdir ${{github.workspace}}/export/lib
        mkdir ${{github.workspace}}/export/doc
    - name: Copy files (not windows)
      if: ${{ !startsWith(matrix.os, 'windows') }}
      run: |
        cp ${{github.workspace}}/build/src/piet-console ${{github.workspace}}/export/bin/
        cp ${{github.workspace}}/build/src/gui/gui ${{github.workspace}}/export/bin/
        cp ${{github.workspace}}/build/src/core/libPietCore.a ${{github.workspace}}/export/lib/
    - name: Copy files (windows)
      if: startsWith(matrix.os, 'windows')
      run: |
        cp ${{github.workspace}}/build/src/${{env.BUILD_TYPE}}/piet-console.exe ${{github.workspace}}/export/bin/
        cp ${{github.workspace}}/build/src/gui/${{env.BUILD_TYPE}}/gui.exe ${{github.workspace}}/export/bin/
        cp ${{github.workspace}}/build/src/core/${{env.BUILD_TYPE}}/PietCore.lib ${{github.workspace}}/export/lib/
        windeployqt ${{github.workspace}}/export/bin/ --release --no-compiler-runtime --no-translations --no-opengl-sw
    - name: Copy docs
      run: cp -r ${{github.workspace}}/build/doc/* ${{github.workspace}}/export/doc/
    - name: Upload build
      uses: actions/upload-artifact@v2
      with:
        name: piet-${{ matrix.os }}
        path: ${{github.workspace}}/build
    - name: Upload export
      uses: actions/upload-artifact@v2
      with:
        name: piet-${{ matrix.os }}-dist
        path: ${{github.workspace}}/export
